package com.soninsony.backgroundthread;

import androidx.appcompat.app.AppCompatActivity;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.media.Image;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;

import com.gkemon.XMLtoPDF.PdfGenerator;
import com.gkemon.XMLtoPDF.PdfGeneratorListener;
import com.gkemon.XMLtoPDF.model.FailureResponse;
import com.gkemon.XMLtoPDF.model.SuccessResponse;

import org.w3c.dom.Document;

import java.io.IOException;
import java.net.MalformedURLException;

public class PDfActivity extends AppCompatActivity {
    private static String FILE = "mnt/sdcard/invoice.pdf"; // add permission in your manifest...

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pdf);
        genRate();

    }







    private void genRate() {

        PdfGenerator.getBuilder()
                .setContext(PDfActivity.this)
                .fromViewIDSource()
                .fromViewID(PDfActivity.this,R.id.ll_latter_pad)
//                .fromLayoutXMLSource()
//                .fromLayoutXML(R.layout.activity_pdf)
//                .fromViewSource()
//                .fromView(findViewById(R.id.ll_lyt))
                /* "fromLayoutXML()" takes array of layout resources.
                 * You can also invoke "fromLayoutXMLList()" method here which takes list of layout resources instead of array. */
                .setFileName("Test-PDF")
                /* It is file name */
                .setFolderNameOrPath("FolderA/FolderB/FolderC")
                .actionAfterPDFGeneration(PdfGenerator.ActionAfterPDFGeneration.OPEN)
                .setPrintingMode(PdfGenerator.PrintingMode.PORTRAIT)
                .build(new PdfGeneratorListener() {
                    @Override
                    public void onFailure(FailureResponse failureResponse) {
                        super.onFailure(failureResponse);
                        /* If pdf is not generated by an error then you will findout the reason behind it
                         * from this FailureResponse. */
                    }
                    @Override
                    public void onStartPDFGeneration() {
                        /*When PDF generation begins to start*/
                    }

                    @Override
                    public void onFinishPDFGeneration() {
                        /*When PDF generation is finished*/
                    }

                    @Override
                    public void showLog(String log) {
                        super.showLog(log);
                        /*It shows logs of events inside the pdf generation process*/
                    }

                    @Override
                    public void onSuccess(SuccessResponse response) {
                        super.onSuccess(response);
                        /* If PDF is generated successfully then you will find SuccessResponse
                         * which holds the PdfDocument,File and path (where generated pdf is stored)*/

                    }
                });

    }
}